language: java
addons:
  sonarcloud:
    organization: "bdomingues-github"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
  - mvn site site:deploy
after_failure:
  - mvn site site:deploy
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
