language: java
addons:
  sonarcloud:
    organization: "bdomingues-github"

install: mvn site site:deploy
before_script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn install
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
